## tf-dif 직접 계산하기

In [2]:
docs = ['오늘 동물원에서 원숭이를 봤어',
       '오늘 동물원에서 코끼리를 봤어 봤어',
       '동물원에서 원숭이에게 바나나를 줬어 바나나를']

doc_ls = [doc.split() for doc in docs]

from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in doc_ls for token in doc]

In [3]:
doc_ls = [doc.split() for doc in docs]

In [9]:
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [10]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))


In [11]:
[word2id[token] for doc in doc_ls for token in doc]

[0, 1, 2, 3, 0, 1, 4, 3, 3, 1, 5, 6, 7, 6]

In [12]:
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이를': 2,
             '봤어': 3,
             '코끼리를': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

In [14]:
len(word2id), len(doc_ls)

(8, 3)

In [26]:
import numpy as np
TDM = np.zeros((len(word2id), len(doc_ls)))
TDM

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
doc_names = ['문서' + str(i) for i in range(len(doc_ls))]
doc_names

['문서0', '문서1', '문서2']

In [28]:
vocab = word2id

In [29]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token], i] += 1
TDM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [31]:
import pandas as pd

In [103]:
df_TDM = pd.DataFrame(TDM, columns = doc_names)
df_TDM['단어'] = vocab
df_TDM=df_TDM.set_index('단어')

In [104]:
df_TDM

문서0  문서1  문서2
단어                  
오늘     1.0  1.0  0.0
동물원에서  1.0  1.0  1.0
원숭이를   1.0  0.0  0.0
봤어     1.0  2.0  0.0
코끼리를   0.0  1.0  0.0
원숭이에게  0.0  0.0  1.0
바나나를   0.0  0.0  2.0
줬어     0.0  0.0  1.0

In [37]:
# TF 계산인데.
df_TDMdf_TDM['문서0'].sum()

4.0

In [117]:
def computeTF(df_TDM):
    tf = []
    col_list = list(df_TDM.columns)
    for col in col_list:
        tf.append(np.array(df_TDM[col] / df_TDM[col].sum()))
    
    return tf
        
# def computeTF(TDM):
#     for i in range(len(vocab)):
#     df_TDM['tf{}'.format(i)]= (df_TDM[col] / df_TDM[col].sum())
    
#     return tf

In [182]:
computeTF(df_TDM).T

AttributeError: 'list' object has no attribute 'T'

In [119]:
df_TDM

문서0  문서1  문서2
단어                  
오늘     1.0  1.0  0.0
동물원에서  1.0  1.0  1.0
원숭이를   1.0  0.0  0.0
봤어     1.0  2.0  0.0
코끼리를   0.0  1.0  0.0
원숭이에게  0.0  0.0  1.0
바나나를   0.0  0.0  2.0
줬어     0.0  0.0  1.0

In [148]:
len(np.array(df_TDM)[0])

3

In [129]:
math.log(-(np.array(df_TDM) / 3))

TypeError: only size-1 arrays can be converted to Python scalars

In [146]:
idf = np.zeros_like(TDM)
idf.shape

(8, 3)

In [89]:
import math

In [177]:
def computeIDF(df_TDM):
    TDM = np.array(df_TDM)
    nun = len(TDM[0])
    for i in range(TDM.shape[0]):
        for j in range(TDM.shape[1]):
            if TDM[i][j] >= 1:
                TDM[i][j]= 1
            
            TDM[i][j] = - math.log((TDM[i][j]+ 1)/nun)

    return TDM


In [178]:
computeIDF(df_TDM)

array([[0.40546511, 0.40546511, 1.09861229],
       [0.40546511, 0.40546511, 0.40546511],
       [0.40546511, 1.09861229, 1.09861229],
       [0.40546511, 0.40546511, 1.09861229],
       [1.09861229, 0.40546511, 1.09861229],
       [1.09861229, 1.09861229, 0.40546511],
       [1.09861229, 1.09861229, 0.40546511],
       [1.09861229, 1.09861229, 0.40546511]])

In [176]:
TDM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [175]:
- math.log(TDM[0][2]/3)
TD

ValueError: math domain error

In [55]:
df_TDM.columns

Index(['문서0', '문서1', '문서2', 'tf0', 'tf1', 'tf2'], dtype='object')

In [64]:
# df_tf['tf{}'.format(i)]=

tf = np.zeros(TDM.shape())

TypeError: 'tuple' object is not callable

In [65]:
TDM.shape

(8, 3)

## 선생님풀이..

In [183]:
docs = ['오늘 동물원에서 원숭이를 봤어',
       '오늘 동물원에서 코끼리를 봤어 봤어',
       '동물원에서 원숭이에게 바나나를 줬어 바나나를']

# 토큰화
doc_ls = [doc.split() for doc in docs]

from collections import defaultdict
# 딕셔너리 만들었고
word2id = defaultdict(lambda : len(word2id))

# 단어하나씩 집어넣기
[word2id[token] for doc in doc_ls for token in doc]

[0, 1, 2, 3, 0, 1, 4, 3, 3, 1, 5, 6, 7, 6]

In [209]:
word2id['봤어']

3

In [185]:
import numpy as np

DTM = np.zeros((len(doc_ls), len(word2id)), dtype = int)     # Document Term  Matrix D - 행 T 열

for i, doc in enumerate(doc_ls):
    for token in doc:
        DTM[i, word2id[token]] += 1

DTM

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

### TF 계싼

TF = 문서내 토크빈도 / 문서내 전체토큰개수

In [191]:
def computeTF(DTM):
    doc_len = len(DTM)
    word_len = len(DTM[0])
    
    tf = np.zeros((doc_len, word_len))
    
    for doc_i in range(doc_len):
        for word_i in range(word_len):
            tf[doc_i, word_i] = DTM[doc_i, word_i]/DTM[doc_i].sum()
            
    return tf

In [192]:
computeTF(DTM)

array([[0.25, 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.2 , 0.  , 0.4 , 0.2 , 0.  , 0.  , 0.  ],
       [0.  , 0.2 , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.2 ]])

### IDF 계산 

IDF = log(총문서수 / 토큰이등장한문서수)

In [197]:
import math

def computeIDF(DTM):
    doc_len = len(DTM)
    word_len = len(DTM[0])
    idf = np.zeros(word_len)
    for i in range(word_len):
        idf[i] = -math.log10(np.count_nonzero(DTM[:, i]) / doc_len)# 모든행에 대허서 i번째 열을 가져온다
        
    return idf

In [198]:
computeIDF(DTM)

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

### TF-IDF 계싼

In [204]:
def computeTFIDF(DTM):
    tf = computeTF(DTM)
    idf = computeIDF(DTM)
    
    tfidf = np.zeros(tf.shape)
    
    for doc_i in range(tf.shape[0]):
        for word_i in range(tf.shape[1]):
            tfidf[doc_i, word_i] = tf[doc_i, word_i] * idf[word_i]
            
    return tfidf

In [205]:
computeTFIDF(DTM)

array([[ 0.04402281, -0.        ,  0.11928031,  0.04402281,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.03521825, -0.        ,  0.        ,  0.0704365 ,  0.09542425,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ,  0.        ,
         0.09542425,  0.1908485 ,  0.09542425]])

In [207]:
import pandas as pd 
sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
tfidf = computeTFIDF(DTM)
pd.DataFrame(tfidf, columns = vocab)

오늘  동물원에서     원숭이를        봤어      코끼리를     원숭이에게      바나나를        줬어
0  0.044023   -0.0  0.11928  0.044023  0.000000  0.000000  0.000000  0.000000
1  0.035218   -0.0  0.00000  0.070437  0.095424  0.000000  0.000000  0.000000
2  0.000000   -0.0  0.00000  0.000000  0.000000  0.095424  0.190849  0.095424

In [210]:
docs

['오늘 동물원에서 원숭이를 봤어', '오늘 동물원에서 코끼리를 봤어 봤어', '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [228]:
from math import log10
import numpy as np
from collections import defaultdict

# q빈도수
def f(t,d):
    return d.count(t)


# tf 계산
def tf(t, d):
    return 0.5 + 0.5*f(t,d) / max([f(w, d) for w in d])


# idf 계산

def idf(t, D):
    num = len(D)
    den =  1 +  len([True for d in D if t in d])
    return 1 + log10(num / den)
    
    
# 공백을 기준으로 토근화
def tokenizer(d):
    return d.split()

# tf-idf 계산
def tfidScore(D):
    D_ls = [tokenizer(d) for d in D]
    vocab = list(set().union(*D_ls))
    word2id = defaultdict(lambda : len(word2id))
    [word2id[v] for v in vocab]
    
    print(word2id)
    
    tfidf = np.zeros((len(D_ls), len(vocab)))
    for i in range(len(D_ls)):
        for t in D_ls[i]:
            tfidf[i, word2od[t]] = tfidf_score(t, D_ls[i], D)
    
    return tfidf, vocab
    

            
    


In [229]:
tfidScore(docs)

defaultdict(<function tfidScore.<locals>.<lambda> at 0x0000028A93823F28>, {'오늘': 0, '코끼리를': 1, '바나나를': 2, '동물원에서': 3, '줬어': 4, '원숭이에게': 5, '원숭이를': 6, '봤어': 7})


NameError: name 'tfidf_score' is not defined

In [ ]:
import pandas as pd
tfidf, vocab = tifdScorer(docs)
pd.DataFrame(tfidf, columns = vocab)