# 9-2 Textrank

문장간 유사성이 있는 경우는 connection이 있다고 생각한다..

![대체 텍스트](https://www.researchgate.net/profile/Khushboo_Thakkar3/publication/232645575/figure/fig1/AS:575720050573312@1514273764062/Sample-graph-build-for-sentence-extraction.png)

## 2.1 TextRank 직접 구현하기 (Matrix 활용)

In [1]:
Text = "딸기 바나나 사과 파인애플. 바나나 사과 딸기 포도. 복숭아 수박. 파인애플 사과 딸기 바나나."

In [2]:
from konlpy.tag import Mecab
mecab = Mecab(dicpath = 'C:\mecab\mecab-ko-dic')

In [9]:
sentences = Text.split('. ')

In [10]:
sentences[-1] = sentences[-1][:-1]

In [11]:
sentences

['딸기 바나나 사과 파인애플', '바나나 사과 딸기 포도', '복숭아 수박', '파인애플 사과 딸기 바나나']

In [6]:

# 문장간 유사도 측정 (자카드 유사도 사용)
def sentence_similarity(sentence1, sentence2):
    set1 = set(mecab.pos(sentence1))
    set2 = set(mecab.pos(sentence2))
    
    return len(set1 & set2) / len(set1 | set2)
    

sentence_similarity('나는 치킨을 좋아해','나는 치킨을 싫어해')

0.6666666666666666

### 2) 그래프 생성

In [ ]:
import numpy as np
    def buildMatrix(sentences):
        score = None
    # 문장별로 그래프 edge를 Matrix 형태로 생성
        weighted_edge = None
    
        return score, weighted_edge

Text = "딸기 바나나 사과 파인애플 수박. 바나나 사과 딸기 포도. 복숭아 수박. 파인애플 사과 딸기 바나나."
buildMatrix(sent_tokenize(Text))    

In [12]:
import numpy as np

In [45]:
def buildMatrix(sentences):
    
    len_sent = len(sentences)

    f_weighted_edge = np.zeros((len_sent, len_sent), np.float32)
    weighted_edge = np.zeros((len_sent, len_sent), np.float32)
    # we must get first score in order to make score
    for i in range(len_sent):
        for j in range(len_sent):
            if not i == j:
                f_weighted_edge[i][j] = sentence_similarity(sentences[i], sentences[j])

    score = f_weighted_edge.sum(axis=1)     
    # print(score)
    # print(weighted_edge)

    for i in range(len_sent):
        for j in range(len_sent):
            
            if not i == j:
                if score[j] == 0:
                    weighted_edge[i][j] = 0
                else:
                    weighted_edge[j][i] = sentence_similarity(sentences[i], sentences[j])/score[j]

    return score, weighted_edge, f_weighted_edge

In [46]:
score, weighted_edge, f_weighted_edge = buildMatrix(sentences)
f_weighted_edge

array([[0. , 0.6, 0. , 1. ],
       [0.6, 0. , 0. , 0.6],
       [0. , 0. , 0. , 0. ],
       [1. , 0.6, 0. , 0. ]], dtype=float32)

In [47]:
weighted_edge

array([[0.        , 0.375     , 0.        , 0.625     ],
       [0.49999997, 0.        , 0.        , 0.49999997],
       [0.        , 0.        , 0.        , 0.        ],
       [0.625     , 0.375     , 0.        , 0.        ]], dtype=float32)

In [44]:
0.6/1.6

0.37499999999999994

In [29]:
1.6 * 0.625 + 0.4999997 * 1.2

1.59999964

### 3) 문장 중요도 계산

In [19]:
def scoring(score, weighted_edge, eps=0.0001, d=0.85, max_iter = 50):
    
    for i in range(max_iter):
        prev_score = np.copy(score)
        score =  (1 - d)  +  d*np.dot(weighted_edge.T, score)
        
        if np.sum(np.fabs(score - prev_score)) <= eps:
            break
                
    return score

In [20]:
gotit = scoring(score, weighted_edge)
gotit

array([1.0807459 , 0.83899546, 0.15      , 1.0807459 ], dtype=float32)

In [99]:
new_score

array([1.4, 1.1, 0. , 1.3], dtype=float32)

### 4) 문서 요약

In [ ]:
import nltk
nltk.download('punkt')

In [ ]:
from nltk.tokenize import sent_tokenize

def summarize(text, n=10):
  pass

In [ ]:
summary = summarize(Text, 3)

for sent in summary :
  print(sent)

## 2.2 TextRank 직접 구현하기 (Graph 활용)

In [2]:
Text = "딸기 바나나 사과 딸기 파인애플. 바나나 사과 딸기. 복숭아 파인애플. 파인애플 사과 딸기 바나나."

### 2) 토큰화

In [3]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
def sentences(text):
    return sent_tokenize(text)

### 3) 자카드 유사도

- 겹치는 토큰의 비율!!  

근데 그러면 score 필요하잖아.. 그러면 어떻게?

- 문장 1 -> 문장 2   


( 문장 1 - 문장2 유사도) / (문장1 전체 유사도 합(0.5 / (0.5 + 0.8 + 0.167) -> 이거 자체가 score!

유사도를 기반으로, 그냥 초기 스코어를 edge 유사도의 합으로 구해(들어온거)  

그 다음 egge 가중치



In [ ]:
from konlpy.tag import Mecab

# 문장간 유사도 측정 (자카드 유사도 사용)
def sentence_similarity(sentence1, sentence2):
  pass

sentence_similarity('나는 치킨을 좋아해','나는 치킨을 싫어해')

In [ ]:
def connect(nodes):
    pass

### 3) 그래프 생성

In [ ]:
import networkx as nx

def rank(nodes,edges):
    passi

### 4) 문서 요약

In [ ]:
def summarize(text,num_summaries=3):
    pass

In [ ]:
summary=summarize(Text, 3)

for sent in summary :
  print(sent)

## 2.3 gensim을 활용한 요약

In [ ]:
print(docs[1])

In [ ]:
from gensim.summarization.summarizer import summarize
summarize(docs[1]).split('\n')