In [1]:
docs = ['오늘 동물원에서 원숭이를 봤어',
       '오늘 동물원에서 코끼리를 봤어 봤어',
       '동물원에서 원숭이에게 바나나를 줬어 바나나를']


In [2]:
doc_ls = [doc.split() for doc in docs]

In [3]:
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [4]:
from collections import defaultdict

In [5]:
word2id = defaultdict(lambda : len(word2id))

In [6]:
[word2id[token]for doc in doc_ls for token in doc]

[0, 1, 2, 3, 0, 1, 4, 3, 3, 1, 5, 6, 7, 6]

In [7]:
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이를': 2,
             '봤어': 3,
             '코끼리를': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

In [8]:
len(word2id), len(doc_ls)

(8, 3)

In [10]:
# Make TDM
import numpy as np
TDM = np.zeros((len(word2id), len(doc_ls)))

In [11]:
TDM

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token], i] += 1
TDM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [14]:
import pandas as pd
doc_names = ['문서0', '문서1', '문서2']
df_TDM = pd.DataFrame(TDM, columns = doc_names)

In [15]:
df_TDM

문서0  문서1  문서2
0  1.0  1.0  0.0
1  1.0  1.0  1.0
2  1.0  0.0  0.0
3  1.0  2.0  0.0
4  0.0  1.0  0.0
5  0.0  0.0  1.0
6  0.0  0.0  2.0
7  0.0  0.0  1.0

In [17]:
vocab = word2id

In [18]:
df_TDM['단어'] = vocab

In [19]:
df_TDM

문서0  문서1  문서2     단어
0  1.0  1.0  0.0     오늘
1  1.0  1.0  1.0  동물원에서
2  1.0  0.0  0.0   원숭이를
3  1.0  2.0  0.0     봤어
4  0.0  1.0  0.0   코끼리를
5  0.0  0.0  1.0  원숭이에게
6  0.0  0.0  2.0   바나나를
7  0.0  0.0  1.0     줬어

In [20]:
df_TDM.set_index('단어')

문서0  문서1  문서2
단어                  
오늘     1.0  1.0  0.0
동물원에서  1.0  1.0  1.0
원숭이를   1.0  0.0  0.0
봤어     1.0  2.0  0.0
코끼리를   0.0  1.0  0.0
원숭이에게  0.0  0.0  1.0
바나나를   0.0  0.0  2.0
줬어     0.0  0.0  1.0

In [31]:
TDM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [32]:
TDM.sum(axis=0)

array([4., 5., 5.])

In [33]:
TDM.sum(axis=1)

array([2., 3., 1., 3., 1., 1., 2., 1.])

In [35]:
TDM / TDM.sum(axis=0)

array([[0.25, 0.2 , 0.  ],
       [0.25, 0.2 , 0.2 ],
       [0.25, 0.  , 0.  ],
       [0.25, 0.4 , 0.  ],
       [0.  , 0.2 , 0.  ],
       [0.  , 0.  , 0.2 ],
       [0.  , 0.  , 0.4 ],
       [0.  , 0.  , 0.2 ]])

In [38]:
(TDM.T / TDM.sum(axis=1)).T

array([[0.5       , 0.5       , 0.        ],
       [0.33333333, 0.33333333, 0.33333333],
       [1.        , 0.        , 0.        ],
       [0.33333333, 0.66666667, 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ]])

In [47]:
np.count_nonzero(TDM[:, 1])

4

In [46]:
TDM[:, 1]

array([1., 1., 0., 2., 1., 0., 0., 0.])

In [45]:
TDM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [49]:
doc_len = len(doc_ls)

In [50]:
doc_len

3

In [51]:
TDM[0, :]

array([1., 1., 0.])

In [53]:
vocab_len = len(word2id)
vocab_len

8

In [63]:
idf = []
idf = np.zeros(vocab_len)
for i in range(vocab_len):
    idf[i] = -math.log10(np.count_nonzero(TDM[i, :]) / doc_len)

In [64]:
idf

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

In [65]:
#
docs = ['오늘 동물원에서 원숭이를 봤어',
       '오늘 동물원에서 코끼리를 봤어 봤어',
       '동물원에서 원숭이에게 바나나를 줬어 바나나를']


우선 내 생각을 정리해보자  
1. docs를 doc_ls로 만들자(token으로)
2. defaultdict를 통해서 (길이) word2id라는 인덱스 설정을 해준다
3. TDM이기때문에, doc_len, word_len을 지정해준다
4. 이제 이걸 만들기 위해 np.zeros를 이용해서 8x3 행렬을 만든다
5. enumerate를 통해, word2id[token], i 를 인덱싱해줘서 += 1을 한다
-------------여기까지가 TDM 만들기-------------
TFIDF
1. 일단 각 문서별로, 합을 구해서(axis=0) 나눠주는 행렬을 만든다
2. 이제 doc_len을통해서 문서 길이 구하고, np.countnonzero(TDM[i, :]를 통해서 모든 열을 뽑아서 나눠준다
3. 그럼 이제 np.zeros를 통해서 빈 array 만들어서
4. tf에서 첫번째 열 뽑고 idf 곱한걸 넣어주고, 이런식으로 진행


In [66]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [68]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이를': 2,
             '봤어': 3,
             '코끼리를': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

In [69]:
doc_len = len(doc_ls)
word_len = len(word2id)
doc_len, word_len

(3, 8)

In [70]:
import numpy as np
TDM = np.zeros((word_len, doc_len))
TDM

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token], i ] += 1
TDM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [72]:
# 이걸 만약 DataFrame
vocab = word2id
col_name = ['문서0', '문서1', '문서2']

In [78]:
import pandas as pd
df_TDM  = pd.DataFrame(TDM, columns=col_name)
df_TDM['단어'] = vocab
df_TDM = df_TDM.set_index(['단어'])
df_TDM

문서0  문서1  문서2
단어                  
오늘     1.0  1.0  0.0
동물원에서  1.0  1.0  1.0
원숭이를   1.0  0.0  0.0
봤어     1.0  2.0  0.0
코끼리를   0.0  1.0  0.0
원숭이에게  0.0  0.0  1.0
바나나를   0.0  0.0  2.0
줬어     0.0  0.0  1.0

In [81]:
# TF 구하기
TDM.sum(axis=0)

array([4., 5., 5.])

In [82]:
TF = TDM / TDM.sum(axis=0)
TF

array([[0.25, 0.2 , 0.  ],
       [0.25, 0.2 , 0.2 ],
       [0.25, 0.  , 0.  ],
       [0.25, 0.4 , 0.  ],
       [0.  , 0.2 , 0.  ],
       [0.  , 0.  , 0.2 ],
       [0.  , 0.  , 0.4 ],
       [0.  , 0.  , 0.2 ]])

In [84]:
# IDF는 특히, -math.log10(np.count_nonzero([/doc_len)
np.count_nonzero(TDM[0, :])

2

In [87]:
import math

idf = np.zeros((word_len))
# print(idf)
for i in range(word_len):
    idf[i] = -math.log10(np.count_nonzero(TDM[i,:])/doc_len)

In [88]:
idf

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

In [91]:
TF[:,0] * idf

array([ 0.04402281, -0.        ,  0.11928031,  0.04402281,  0.        ,
        0.        ,  0.        ,  0.        ])

In [92]:
tf_idf = np.zeros((word_len, doc_len))
tf_idf

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
for i in range(doc_len):
    tf_idf[:, i] = TF[:, i] * idf
    

In [94]:
tf_idf

array([[ 0.04402281,  0.03521825,  0.        ],
       [-0.        , -0.        , -0.        ],
       [ 0.11928031,  0.        ,  0.        ],
       [ 0.04402281,  0.0704365 ,  0.        ],
       [ 0.        ,  0.09542425,  0.        ],
       [ 0.        ,  0.        ,  0.09542425],
       [ 0.        ,  0.        ,  0.1908485 ],
       [ 0.        ,  0.        ,  0.09542425]])

In [1]:
import numpy as np
import pandas as pd
from collections import defaultdict

In [10]:
docs = ['오늘 동물원에서 원숭이를 봤어',
       '오늘 동물원에서 코끼리를 봤어 봤어',
       '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [54]:
doc_ls = [ doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [55]:
from collections import defaultdict

In [56]:
word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이를': 2,
             '봤어': 3,
             '코끼리를': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

In [59]:
TDM = np.zeros((len(word2id), len(doc_ls)))
TDM

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token],i] += 1
TDM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [64]:
TF = TDM / TDM.sum(axis=0)
TF

array([[0.25, 0.2 , 0.  ],
       [0.25, 0.2 , 0.2 ],
       [0.25, 0.  , 0.  ],
       [0.25, 0.4 , 0.  ],
       [0.  , 0.2 , 0.  ],
       [0.  , 0.  , 0.2 ],
       [0.  , 0.  , 0.4 ],
       [0.  , 0.  , 0.2 ]])

In [67]:
IDF = np.zeros((len(word2id))
               
for i in range(len(word2id)):
               IDF[i] =-math.log10(np.count_nonzero(TDM[i, :]) /len(doc_ls))
IDF

SyntaxError: invalid syntax (<ipython-input-67-db880566cc24>, line 3)

In [68]:
for i in range(len(word2id)):
    IDF[i] =-math.log10(np.count_nonzero(TDM[i, :]) /len(doc_ls))

In [69]:
IDF

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

In [70]:
TFIDF = np.zeros((len(word2id), len(doc_ls)))
for i in range(len(doc_ls)):
    TFIDF[:, i ] = TF[:, i] * IDF

In [71]:
TFIDF

array([[ 0.04402281,  0.03521825,  0.        ],
       [-0.        , -0.        , -0.        ],
       [ 0.11928031,  0.        ,  0.        ],
       [ 0.04402281,  0.0704365 ,  0.        ],
       [ 0.        ,  0.09542425,  0.        ],
       [ 0.        ,  0.        ,  0.09542425],
       [ 0.        ,  0.        ,  0.1908485 ],
       [ 0.        ,  0.        ,  0.09542425]])

In [72]:

word_embedding_dic = {
    '사과' : [1.0, 0.5],
    '바나나' : [0.9, 1.2],
    '원숭이' : [0.5, 1.5]
}
def cosine_similarity(x, y):
    nominator = np.dot(x, y)
    denominator = np.linalg.norm(x)*np.linalg.norm(y)
    return nominator/ denominator
cosine_similarity(word_embedding_dic['사과'], word_embedding_dic['바나나'])

0.8944271909999159

In [73]:
a = [1,2]
b = [3,4]
np.dot(a,b)

11

In [75]:
np.linalg.norm(a)

2.23606797749979

In [77]:
np.array(a) - np.array(b)

array([-2, -2])

In [ ]:
np.sqrt(np.array(a) - np.array(b))

In [81]:
def euclidean(x,y):
    x = np.array(x)
    y = np.array(y)
    return np.sqrt(np.sum((x-y)**2))

In [82]:
euclidean(a,b)

2.8284271247461903

In [83]:
def cos(x,y):
    x = np.array(x)
    y = np.array(y)
    return (np.dot(x,y))/(np.linalg.norm(x) * np.linalg.norm(y))

In [84]:
cos(a,b)

0.9838699100999074

In [86]:
# 1. 유클리드
import numpy as np

a = [1,2]
b = [3,4]

np.sqrt((np.sum((np.array(a) - np.array(b))**2)))

2.8284271247461903

In [87]:
# 2. 자카드 유사도

a = [1,2]
b = [3,4]

up = np.dot(a,b)
down = np.linalg.norm(a)*np.linalg.norm(b)
up/down

0.9838699100999074

In [89]:
# . 자카드 유사도

a = [1,2]
b = [2,3]

len(set(a)&set(b))/len(set(a)|set(b))

0.3333333333333333

In [90]:
docs = ['오늘 동물원에서 원숭이를 봤어',
       '오늘 동물원에서 코끼리를 봤어 봤어',
       '동물원에서 원숭이에게 바나나를 줬어 바나나를']
import numpy as np
import pandas as pd
from collections import defaultdict

In [91]:
doc_ls = [doc.split() for doc in docs]


In [92]:
word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이를': 2,
             '봤어': 3,
             '코끼리를': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

In [97]:
DTM = np.zeros((len(word2id), len(doc_ls)))
DTM

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:
for i, sent in enumerate(doc_ls):
    for token in sent:
        DTM[word2id[token], i] += 1
        


In [99]:
DTM

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.]])

In [100]:
TF = DTM / DTM.sum(axis=0)

In [101]:
TF

array([[0.25, 0.2 , 0.  ],
       [0.25, 0.2 , 0.2 ],
       [0.25, 0.  , 0.  ],
       [0.25, 0.4 , 0.  ],
       [0.  , 0.2 , 0.  ],
       [0.  , 0.  , 0.2 ],
       [0.  , 0.  , 0.4 ],
       [0.  , 0.  , 0.2 ]])

In [104]:
len(doc_ls)
import math

IDF  =  np.zeros(len(word2id))
for i in range(len(word2id)):
    IDF[i] = -math.log10(np.count_nonzero(TDM[i,:])/len(doc_ls))


In [105]:
IDF

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

In [106]:
TFIDF = np.zeros((len(word2id), len(doc_ls)))
for i in range(len(doc_ls)):
    TFIDF[:,i] = TF[:,i]*IDF

In [108]:
TFIDF

array([[ 0.04402281,  0.03521825,  0.        ],
       [-0.        , -0.        , -0.        ],
       [ 0.11928031,  0.        ,  0.        ],
       [ 0.04402281,  0.0704365 ,  0.        ],
       [ 0.        ,  0.09542425,  0.        ],
       [ 0.        ,  0.        ,  0.09542425],
       [ 0.        ,  0.        ,  0.1908485 ],
       [ 0.        ,  0.        ,  0.09542425]])